### ISSUE TITLE
Fix some stuff with the new centroids

### ISSUE THREAD

**Issue by fredtal** [kaycole/fish_shift#59]
Some stuff is up with the new centroids matrix: 
 -  it's twice as long as it needs to be, with the second half all blank rows.
 - what happened to triplength?
 - what happened to permitcount?
 - centroids is all chr data not num
 - there's no pots in centroids.  is pots all in lobster?

**Comment by mikprov** [comment]
Good to note. I'll try to take a stab at these this afternoon/evening.

**Comment by fredtal** [comment]
Okay cool.  I can also do it when I get back.  All the relevant code that might need editing should be in centroids.R.  To run it, use run_centroids.  Run_centroids requires the across_along and fisher_depth files.  Across_along is already in /nfs/fish-fisher-data, but the cluster hasn't finished generating the fisher_depth file yet so I've commented out all the sections that involve depth.

**Comment by kaycole** [comment]
Stop messing with my code T!! :P we'll first off its a function but it looks like you changed all the 'data' variables to 'casdata' in the function but the function still has the input of 'data'... I'll change that and test it out.

**Comment by kaycole** [comment]
These aren't working in run_centroids.R on the sesync Rstudio:
source(paste(codedir, "treat_data.R", sep="/"))
source(paste(codedir, "centroids.R", sep="/"))
not sure how to fix those

also in run_centroids when you replace casdata and do the treatdata, you get rid of the across and along rows so they are not available for the centroids function (data$across = NULL)... still working on fixing things
casdata <- cbind(casdata, along_across)
casdata <-treat_data(casdata) # no longer has across and along

**Comment by kaycole** [comment]
Should be good now, I think the main errors were that the function centroids(data) had the variable 'casdata' inside the loop instead of 'data' so it wasn't working properly (Talia leave it as data), and since you didn't change all over them it was still calling data$triplength instead of casdata$triplength and things like that so it was a mess. Also, in defining the variables in treat_data, the along and across shelf variables were called "1" and "2" so now they have names and can be called in the loop. Worked on a subset or casdata, but I can can run the whole thing now so that it saves. I'll look at your other concerns when it runs as a whole because the subset appears to be the right size and have all the variables we defined in 'centers'

**Comment by kaycole** [comment]
OK, its finished and saved.  There are a lot of NA's in the columns where we use mean and sd but not in the centers of biomass or min/max lat/lon, in Matlab theres a nanmean function so that we dont get a mean of NA, is there something similar to that in R that we could use instead or should i add something in the loop that cuts the data to not use data when there are NA's in the calculations?

**Comment by emfuller** [comment]
You can add the argument "na.rm = TRUE" to drop NAs from mean/sd
calculations.

So it would be mean(data, na.rm = TRUE)

**Comment by fredtal** [comment]
Sorry @kaycole!  Thank you for fixing all my problems!  I added the na.rms.

**Comment by fredtal** [comment]
centroids is still half empty!  will check when i have a chance.

**Comment by kaycole** [comment]
running centroids now, we'll see if these issues are still happening

**Comment by fredtal** [comment]
okay, fixed: 
 - empty NA rows at bottom
 - calculated trip_length (mean(trip_days))
 - size_fleet (=permitcount) is in there
 - converted numeric columns to number
 - checked other.pots_and_traps are in there.
