### ISSUE TITLE
generate NatCap fishing sheds

### ISSUE THREAD

**Issue by emfuller** [kaycole/fish_shift#72]
Emma was going to write the code for a single community, Talia was going to generalize to loop through all communities and save in a rational way. :whale2:

**Comment by emfuller** [comment]
@fredtal: I tried to comment the crap out of the code. 

If you're feeling confused by the logic, let me know. I think I could explain it in 2 minutes, and over email/via comments might be much more difficult to understand.

**Comment by fredtal** [comment]
I wrote code and generated a file with a raster map for each community (with at least reasonable boundaries by state for now).  

Still to do: 
 - add the 50% and 75% PVCs to those maps
 - add the moving centroid to those maps
 - save each raster object, and each 50% and 75% polygons to an object that can be exported.  (I was thinking a list, with 1 raster and 2 polygons, but am open to other ideas.)  

@emfuller if you want to do it in the next few days, go for it.  Otherwise I'll take a stab when I get back next week.

**Comment by emfuller** [comment]
major changes: drop NA communities, and tif file name has average number of vessels in community, and number of trips.
